name: food_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.4.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0

  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

  # OnBoarding Screen :
  introduction_screen: ^3.1.7

  # Otp screen :
  pin_code_fields: ^7.4.0

  # Main bottomNavigationBar
  google_nav_bar: ^5.0.6
  json_serializable: ^6.6.1
  
  lottie: ^2.3.0
  cherry_toast: ^1.1.0
  shared_preferences: ^2.0.20  
  get_it: ^7.2.0
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  flutter_slidable: ^3.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2


flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/lottie/
