// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm9vwc2_7djgt4I4vW61u-QsDhUNSeGCA',
    appId: '1:796473561774:web:629223219a23a94efed33f',
    messagingSenderId: '796473561774',
    projectId: 'food-app-chihab',
    authDomain: 'food-app-chihab.firebaseapp.com',
    storageBucket: 'food-app-chihab.appspot.com',
    measurementId: 'G-CBM9R8GV7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCx9jqsWG_FMLPFIpTgmJRRNVdikJu6mk',
    appId: '1:796473561774:android:9c6a01c83546b182fed33f',
    messagingSenderId: '796473561774',
    projectId: 'food-app-chihab',
    storageBucket: 'food-app-chihab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUoAl9pz_z2Vnp3XZCWTZsjz1Xri5MACI',
    appId: '1:796473561774:ios:d4c9ab0bdd2bfee8fed33f',
    messagingSenderId: '796473561774',
    projectId: 'food-app-chihab',
    storageBucket: 'food-app-chihab.appspot.com',
    androidClientId: '796473561774-dj61dacjh1c2tsvl2565kgvfm5bgb17m.apps.googleusercontent.com',
    iosClientId: '796473561774-1skhn2conuu7vgdhbvuvhd9f8kkmn9ig.apps.googleusercontent.com',
    iosBundleId: 'com.chihabdev.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUoAl9pz_z2Vnp3XZCWTZsjz1Xri5MACI',
    appId: '1:796473561774:ios:0456a217f0c672c1fed33f',
    messagingSenderId: '796473561774',
    projectId: 'food-app-chihab',
    storageBucket: 'food-app-chihab.appspot.com',
    androidClientId: '796473561774-dj61dacjh1c2tsvl2565kgvfm5bgb17m.apps.googleusercontent.com',
    iosClientId: '796473561774-f0jk7ndna72np5g06umttkpe82li8kki.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );
}
